### ISSUE TITLE
Sémantique du html home.php

### ISSUE THREAD

**Issue by mcl56890** [chaigwen-2906/bibliotheque-en-ligne#36]
Je ne vois aucune section ?????
Il aurait été intéressant de mettre des section à la place des <div class="articles">

h1: le titre ici n'est pas significatif ... Il serait logique d'y trouver le mot livre !

Les img --> attention elles n'ont pas de alt !!! c'est dommage

**Comment by chaigwen-2906** [comment]
j'ai remplacer les div par les sections (c'était prévu): je vais revérifier toutes ma sémantique a la fin
de mon site.
le h1 j'ai changer Merci j'avais pas penser.
Toutes les img sont renommer en alt et title( c'était aussi prévu) mes merci sa évite d'oublier
